/* The following code was generated by JFlex 1.4.3 on 5/17/23, 9:10 PM */

package codigo;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/17/23, 9:10 PM from the specification file
 * <tt>D:/NetBeansProjects/CompiladoresP/src/codigo/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  5,  0,  0,  3,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3,  0,  0, 10,  0, 14,  0,  0,  6,  8,  0, 22,  3,  7,  0,  4, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2, 37,  0, 21,  0, 13, 11, 
    12,  1,  1, 23, 24,  1, 38,  1,  1,  1,  1,  1,  1, 41,  1,  1, 
    33,  9, 34,  1,  1,  1, 40,  1,  1,  1,  1,  0,  0,  0,  0,  1, 
     0, 16, 36, 20, 35, 25,  1,  1, 32, 28,  1,  1, 26, 15, 29, 18, 
    19, 39, 27, 17, 31, 30,  1,  1,  1,  1,  1,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\2\1\1\2\2\1"+
    "\1\4\1\0\1\5\1\6\1\7\1\10\2\11\1\12"+
    "\1\2\1\13\1\14\2\0\1\3\35\0\1\15\5\0"+
    "\1\16\5\0\1\17\14\0\1\20\1\0\1\21\1\22"+
    "\11\0\1\23\1\0\1\24\2\0\1\25\2\0\1\26"+
    "\11\0\1\27\1\0\1\30\7\0\1\31\1\0\1\32"+
    "\1\0\1\33\1\34\2\0\1\35";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\52\0\u01f8\0\52\0\52"+
    "\0\u0222\0\52\0\52\0\u024c\0\52\0\52\0\u0276\0\u02a0"+
    "\0\52\0\u02ca\0\u02f4\0\u031e\0\u0348\0\u0372\0\u039c\0\u03c6"+
    "\0\u03f0\0\u041a\0\u0444\0\u046e\0\u0498\0\u04c2\0\u04ec\0\u0516"+
    "\0\u0540\0\u056a\0\u0594\0\u05be\0\u05e8\0\u0612\0\u063c\0\u0666"+
    "\0\u0690\0\u06ba\0\u06e4\0\u070e\0\u0738\0\u0762\0\52\0\u078c"+
    "\0\u07b6\0\u07e0\0\u080a\0\u0834\0\52\0\u085e\0\u0888\0\u08b2"+
    "\0\u08dc\0\u0906\0\52\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8"+
    "\0\u0a02\0\u0a2c\0\u0a56\0\u0a80\0\u0aaa\0\u0ad4\0\u0afe\0\u0b28"+
    "\0\u0b52\0\u0b7c\0\52\0\u0ba6\0\u0bd0\0\u0bfa\0\u0c24\0\u0c4e"+
    "\0\u0c78\0\u0ca2\0\u0ccc\0\u0cf6\0\52\0\u0d20\0\u0d4a\0\u0d74"+
    "\0\u0d9e\0\u0dc8\0\u0df2\0\u0e1c\0\u0e46\0\u0e70\0\u0e9a\0\u0ec4"+
    "\0\u0eee\0\u0f18\0\u0f42\0\u0f6c\0\u0f96\0\u0fc0\0\52\0\u0fea"+
    "\0\52\0\u1014\0\u103e\0\u1068\0\u1092\0\u10bc\0\u10e6\0\u1110"+
    "\0\52\0\u113a\0\52\0\u1164\0\52\0\52\0\u118e\0\u11b8"+
    "\0\52";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\2\2"+
    "\1\10\3\2\1\11\1\12\6\3\2\2\16\3\1\2"+
    "\4\3\53\0\2\3\6\0\1\3\5\0\6\3\2\0"+
    "\16\3\1\0\4\3\2\0\1\4\52\0\1\5\1\0"+
    "\1\5\50\0\1\13\54\0\1\14\43\0\2\3\4\0"+
    "\1\15\1\0\1\3\1\16\1\17\1\20\1\21\1\0"+
    "\6\3\1\22\1\23\1\24\15\3\1\0\4\3\15\0"+
    "\1\25\52\0\1\26\33\0\5\13\1\0\44\13\2\0"+
    "\1\27\64\0\1\22\7\0\1\22\41\0\1\22\35\0"+
    "\2\3\4\0\1\30\1\0\1\3\5\0\6\3\2\0"+
    "\16\3\1\0\4\3\2\0\1\27\5\0\1\31\62\0"+
    "\1\32\1\0\1\33\1\34\2\0\1\35\1\36\10\0"+
    "\1\37\1\40\3\0\1\41\1\0\1\42\1\43\20\0"+
    "\1\44\51\0\1\45\51\0\1\46\71\0\1\47\42\0"+
    "\1\50\54\0\1\51\46\0\1\52\40\0\1\53\51\0"+
    "\1\54\65\0\1\55\47\0\1\56\40\0\1\57\47\0"+
    "\1\60\66\0\1\61\41\0\1\62\47\0\1\63\52\0"+
    "\1\64\72\0\1\65\40\0\1\66\40\0\1\67\63\0"+
    "\1\70\37\0\1\71\63\0\1\72\36\0\1\73\62\0"+
    "\1\74\52\0\1\75\52\0\1\76\50\0\1\77\52\0"+
    "\1\100\60\0\1\101\15\0\1\102\35\0\1\103\26\0"+
    "\1\104\52\0\1\105\46\0\1\106\70\0\1\107\46\0"+
    "\1\110\35\0\1\111\51\0\1\112\54\0\1\113\22\0"+
    "\1\114\40\0\1\115\52\0\1\116\46\0\1\117\47\0"+
    "\1\120\44\0\1\121\60\0\1\122\63\0\1\123\26\0"+
    "\1\124\63\0\1\125\46\0\1\126\63\0\1\127\26\0"+
    "\1\130\40\0\1\131\62\0\1\132\40\0\1\133\75\0"+
    "\1\134\53\0\1\135\53\0\1\136\34\0\1\137\53\0"+
    "\1\140\73\0\1\141\36\0\1\142\64\0\1\143\52\0"+
    "\1\144\22\0\1\145\40\0\1\146\76\0\1\147\51\0"+
    "\1\150\24\0\1\151\76\0\1\152\53\0\1\153\22\0"+
    "\1\154\110\0\1\155\25\0\1\156\64\0\1\157\62\0"+
    "\1\160\40\0\1\161\45\0\1\162\66\0\1\163\37\0"+
    "\1\164\52\0\1\165\50\0\1\166\24\0\1\167\76\0"+
    "\1\170\52\0\1\171\45\0\1\172\55\0\1\173\37\0"+
    "\1\174\63\0\1\175\35\0\1\176\50\0\1\177\52\0"+
    "\1\200\52\0\1\201\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4578];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\11\1\1\0\1\11\1\1\2\11\1\1"+
    "\2\11\1\1\2\11\2\0\1\11\35\0\1\11\5\0"+
    "\1\11\5\0\1\11\14\0\1\1\1\0\1\1\1\11"+
    "\11\0\1\11\1\0\1\1\2\0\1\1\2\0\1\1"+
    "\11\0\1\11\1\0\1\11\7\0\1\11\1\0\1\11"+
    "\1\0\2\11\2\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 15: 
          { return new Symbol(sym.If, yychar, yyline, yytext());
          }
        case 30: break;
        case 17: 
          { return new Symbol(sym.For, yychar, yyline, yytext());
          }
        case 31: break;
        case 10: 
          { return new Symbol(sym.Concatenar, yychar, yyline, yytext());
          }
        case 32: break;
        case 24: 
          { return new Symbol(sym.forFin, yychar, yyline, yytext());
          }
        case 33: break;
        case 13: 
          { return new Symbol(sym.Atributo, yychar, yyline, yytext());
          }
        case 34: break;
        case 16: 
          { return new Symbol(sym.While, yychar, yyline, yytext());
          }
        case 35: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 36: break;
        case 14: 
          { return new Symbol(sym.CumpleBloque, yychar, yyline, yytext());
          }
        case 37: break;
        case 27: 
          { return new Symbol(sym.ClaseFin, yychar, yyline, yytext());
          }
        case 38: break;
        case 22: 
          { return new Symbol(sym.Clase, yychar, yyline, yytext());
          }
        case 39: break;
        case 7: 
          { return new Symbol(sym.Resta, yychar, yyline, yytext());
          }
        case 40: break;
        case 12: 
          { return new Symbol(sym.Porcentaje, yychar, yyline, yytext());
          }
        case 41: break;
        case 23: 
          { return new Symbol(sym.FinWhile, yychar, yyline, yytext());
          }
        case 42: break;
        case 21: 
          { return new Symbol(sym.Constructor, yychar, yyline, yytext());
          }
        case 43: break;
        case 3: 
          { return new Symbol(sym.digito, yychar, yyline, yytext());
          }
        case 44: break;
        case 9: 
          { return new Symbol(sym.Op_Relacional, yychar, yyline, yytext());
          }
        case 45: break;
        case 20: 
          { return new Symbol(sym.DoWhile, yychar, yyline, yytext());
          }
        case 46: break;
        case 8: 
          { return new Symbol(sym.Multiplicacion, yychar, yyline, yytext());
          }
        case 47: break;
        case 29: 
          { return new Symbol(sym.IfElse, yychar, yyline, yytext());
          }
        case 48: break;
        case 11: 
          { return new Symbol(sym.Asignacion, yychar, yyline, yytext());
          }
        case 49: break;
        case 19: 
          { return new Symbol(sym.FinIf, yychar, yyline, yytext());
          }
        case 50: break;
        case 26: 
          { return new Symbol(sym.ConstructorFin, yychar, yyline, yytext());
          }
        case 51: break;
        case 28: 
          { return new Symbol(sym.Declaracion, yychar, yyline, yytext());
          }
        case 52: break;
        case 5: 
          { return new Symbol(sym.Division, yychar, yyline, yytext());
          }
        case 53: break;
        case 25: 
          { return new Symbol(sym.DoWhileFin, yychar, yyline, yytext());
          }
        case 54: break;
        case 2: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 55: break;
        case 4: 
          { /*Ignore*/
          }
        case 56: break;
        case 6: 
          { return new Symbol(sym.Suma, yychar, yyline, yytext());
          }
        case 57: break;
        case 18: 
          { return new Symbol(sym.Salida, yychar, yyline, yytext());
          }
        case 58: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
