
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 18 20:21:34 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int vString = 21;
  public static final int ClaseFin = 53;
  public static final int Entero = 18;
  public static final int DoWhileFin = 38;
  public static final int Boleano = 22;
  public static final int PuntoComa = 15;
  public static final int Coma = 14;
  public static final int Llave_c = 57;
  public static final int Constructor = 52;
  public static final int finF = 34;
  public static final int Llave_a = 56;
  public static final int If = 26;
  public static final int tCierre = 46;
  public static final int Atributo = 54;
  public static final int Clase = 51;
  public static final int Concatenar = 16;
  public static final int TipoEntero = 39;
  public static final int Asignacion = 6;
  public static final int Corchete_c = 10;
  public static final int FinIf = 27;
  public static final int Corchete_a = 9;
  public static final int hastaW = 30;
  public static final int Op_Relacional = 8;
  public static final int TipoLen = 43;
  public static final int While = 29;
  public static final int Division = 5;
  public static final int Flotante = 20;
  public static final int TipoPisto = 41;
  public static final int Parentesis_c = 12;
  public static final int Parentesis_a = 11;
  public static final int For = 32;
  public static final int Modificadores_Acceso = 24;
  public static final int EOF = 0;
  public static final int DosPuntos = 47;
  public static final int forFin = 36;
  public static final int error = 1;
  public static final int tApertura = 45;
  public static final int funcion = 23;
  public static final int Identificador = 48;
  public static final int TipoCentavo = 42;
  public static final int Salida = 25;
  public static final int LlamaFuncion = 44;
  public static final int Resta = 3;
  public static final int Porcentaje = 7;
  public static final int DoWhile = 37;
  public static final int Verdadero = 40;
  public static final int pasoF = 35;
  public static final int Multiplicacion = 4;
  public static final int Decimal = 19;
  public static final int desdeF = 33;
  public static final int Declaracion = 17;
  public static final int FinWhile = 31;
  public static final int Suma = 2;
  public static final int digito = 49;
  public static final int ConstructorFin = 55;
  public static final int CumpleBloque = 50;
  public static final int IfElse = 28;
  public static final int Comillas = 13;
}

